<?php

namespace App\Http\Requests\Constituicao;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class CriarConstituicaoRequest extends FormRequest
{
    public function rules(): array
    {
        return [
            'prioridade' => ['required', Rule::in(['PRIORIDADE BAIXA', 'PRIORIDADE ALTA', 'URGENTE'])],
            'nome_empresarial' => 'required',
            'nome_empresarial2' => 'present',
            'nome_empresarial3' => 'present',
            'nome_fantasia' => 'present',
            'cep' => 'required',
            'logradouro' => 'required',
            'bairro' => 'required',
            'localidade' => 'required',
            'uf' => 'required',
            'numero' => 'required',
            'referencia' => 'present',
            'tipo_complemento' => ['nullable', Rule::in([
                'ANDAR',
                'ANEXO',
                'APARTAMENTO',
                'ARMAZEM',
                'BANCA',
                'BARRACÃO',
                'CAIXA POSTAL',
                'CASA',
                'CONDOMINIO',
                'CONJUNTO',
                'EDIFICIO',
                'FUNDOS',
                'GALPAO',
                'GARAGEM',
                'LETRA',
                'LOJA',
                'LOTE',
                'MEZANINO',
                'NIVEL',
                'PAVILHAO',
                'PAVIMENTO',
                'PILOTIS',
                'QUADRA',
                'QUILOMETRO',
                'QUIOSQUE',
                'SALA',
                'SETOR',
                'SOBRELOJA',
                'STAND',
                'SUBSOLO',
                'TERREO'
            ])],
            'complemento' => 'present',
            'tipo_complemento2' => ['nullable', Rule::in([
                'ANDAR',
                'ANEXO',
                'APARTAMENTO',
                'ARMAZEM',
                'BANCA',
                'BARRACÃO',
                'CAIXA POSTAL',
                'CASA',
                'CONDOMINIO',
                'CONJUNTO',
                'EDIFICIO',
                'FUNDOS',
                'GALPAO',
                'GARAGEM',
                'LETRA',
                'LOJA',
                'LOTE',
                'MEZANINO',
                'NIVEL',
                'PAVILHAO',
                'PAVIMENTO',
                'PILOTIS',
                'QUADRA',
                'QUILOMETRO',
                'QUIOSQUE',
                'SALA',
                'SETOR',
                'SOBRELOJA',
                'STAND',
                'SUBSOLO',
                'TERREO'
            ])],
            'complemento2' => 'present',
            'tipo_complemento3' => ['nullable', Rule::in([
                'ANDAR',
                'ANEXO',
                'APARTAMENTO',
                'ARMAZEM',
                'BANCA',
                'BARRACÃO',
                'CAIXA POSTAL',
                'CASA',
                'CONDOMINIO',
                'CONJUNTO',
                'EDIFICIO',
                'FUNDOS',
                'GALPAO',
                'GARAGEM',
                'LETRA',
                'LOJA',
                'LOTE',
                'MEZANINO',
                'NIVEL',
                'PAVILHAO',
                'PAVIMENTO',
                'PILOTIS',
                'QUADRA',
                'QUILOMETRO',
                'QUIOSQUE',
                'SALA',
                'SETOR',
                'SOBRELOJA',
                'STAND',
                'SUBSOLO',
                'TERREO'
            ])],
            'complemento3' => 'present',
            'telefone' => 'required',
            'email' => 'required|email',
            'tipo_societario' => ['required', Rule::in(['LTDA', 'S.A', 'EI', 'SIMPLES'])],
            'capital_social' => 'required',
            'data_integralizacao' => 'required|date',
            'clausula_restritiva' => 'present',
            'porte' => ['required', Rule::in(['ME', 'EPP', 'DEMAIS'])],
            'simples' => ['required', Rule::in(['SIM', 'NÃO', 'NÃO DEFINIDO'])],
            'area_imovel' => 'required',
            'pavimentos' => 'required|numeric',
            'outra_edificacao' => ['required', Rule::in(['SIM', 'NÃO'])],
            'edificacao' => 'present',
            'natureza_imovel' => ['required', Rule::in(['RURAL', 'URBANA', 'SEM REGULARIZAÇÃO'])],
            'inscricao_imovel' => 'present',
            'tipo_imovel' => ['required', Rule::in(['PROPRIO','CEDIDO','ALUGADO','COMODATO','CONDOMINIO','OCUPANTE','ESPOLIO','PARCERIA','ARRENDADO','USUFRUTO','DOADO'])],
            'objeto' => 'required',
            'cnae' => 'required',
            'advogado' => ['required', Rule::in(['SIM', 'NÃO'])],
            'advogado_oab' => 'present',
            'assinatura_contrato' => ['required', Rule::in(['GOV.BR', 'CERTIFICADO DIGITAL'])],
            'senha_govbr' => 'present',
            'honorario_observacao' => 'present',
            'honorario_extra' => 'present',
            'files' => 'nullable|array',
            'files.*' => 'file|mimes:png,jpeg,jpg,gif,pdf'
        ];
    }
}
